# Load spatialdata object

In [1]:
import anndata as ad
import spatialdata as sd

/opt/anaconda3/envs/sopa/lib/python3.10/site-packages/dask/dataframe/__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
  warnings.warn(

We read the MIBI-tof data. We use spatialdata readers for this

In [3]:
sdata=sd.read_zarr('../../../data/mibitof.zarr')

version mismatch: detected: RasterFormatV02, requested: FormatV04
/opt/anaconda3/envs/sopa/lib/python3.10/site-packages/zarr/creation.py:614: UserWarning: ignoring keyword argument 'read_only'
  compressor, fill_value = _kwargs_compat(compressor, fill_value, kwargs)
version mismatch: detected: RasterFormatV02, requested: FormatV04
version mismatch: detected: RasterFormatV02, requested: FormatV04

We can see how this object contains three different datasets (point8,point16 and point23), each containing both images (3 channels each) and labels.

We also observed the segmented cells in 'table'. We can see that it contans 36 channels, indicating that we don't have all images for this dataset. Likely only morphologic one

 This meands we

In [4]:
sdata

SpatialData object, with associated Zarr store: /Users/sergio/Documents/jnotebooks/sprot_hackathon/data/mibitof.zarr
├── Images
│     ├── 'point8_image': DataArray[cyx] (3, 1024, 1024)
│     ├── 'point16_image': DataArray[cyx] (3, 1024, 1024)
│     └── 'point23_image': DataArray[cyx] (3, 1024, 1024)
├── Labels
│     ├── 'point8_labels': DataArray[yx] (1024, 1024)
│     ├── 'point16_labels': DataArray[yx] (1024, 1024)
│     └── 'point23_labels': DataArray[yx] (1024, 1024)
└── Tables
      └── 'table': AnnData (3309, 36)
with coordinate systems:
    ▸ 'point8', with elements:
        point8_image (Images), point8_labels (Labels)
    ▸ 'point16', with elements:
        point16_image (Images), point16_labels (Labels)
    ▸ 'point23', with elements:
        point23_image (Images), point23_labels (Labels)

We can see how the info of segmented cells looks like. As you can see, we have cells from each sample (divided by point). We also have cell types annotated.

In [6]:
sdata['table'].obs

,row_num,point,cell_id,X1,center_rowcoord,center_colcoord,cell_size,category,donor,Cluster,batch,library_id
9376-1,9479,8,2,65222.0,37.0,6.0,474.0,carcinoma,90de,Epithelial,1,point8_labels
9377-1,9480,8,4,65224.0,314.0,3.0,126.0,carcinoma,90de,Epithelial,1,point8_labels
9378-1,9481,8,5,65225.0,407.0,6.0,398.0,carcinoma,90de,Epithelial,1,point8_labels
9379-1,9482,8,6,65226.0,439.0,20.0,1749.0,carcinoma,90de,Epithelial,1,point8_labels
9380-1,9483,8,7,65227.0,479.0,6.0,407.0,carcinoma,90de,Imm_other,1,point8_labels
...,...,...,...,...,...,...,...,...,...,...,...,...
4270-0,4322,23,1479,61793.0,519.0,1018.0,125.0,carcinoma,21d7,Tcell_CD4,0,point23_labels
4271-0,4323,23,1480,61794.0,929.0,1018.0,190.0,carcinoma,21d7,Imm_other,0,point23_labels
4272-0,4324,23,1481,61795.0,999.0,1019.0,173.0,carcinoma,21d7,Imm_other,0,point23_labels
4273-0,4325,23,1482,61796.0,322.0,1018.0,181.0,carcinoma,21d7,Myeloid_CD11c,0,point23_labels
4274-0,4326,23,1483,61797.0,785.0,1019.0,178.0,carcinoma,21d7,Tcell_CD4,0,point23_labels

,row_num,point,cell_id,X1,center_rowcoord,center_colcoord,cell_size,category,donor,Cluster,batch,library_id
9376-1,9479,8,2,65222.0,37.0,6.0,474.0,carcinoma,90de,Epithelial,1,point8_labels
9377-1,9480,8,4,65224.0,314.0,3.0,126.0,carcinoma,90de,Epithelial,1,point8_labels
9378-1,9481,8,5,65225.0,407.0,6.0,398.0,carcinoma,90de,Epithelial,1,point8_labels
9379-1,9482,8,6,65226.0,439.0,20.0,1749.0,carcinoma,90de,Epithelial,1,point8_labels
9380-1,9483,8,7,65227.0,479.0,6.0,407.0,carcinoma,90de,Imm_other,1,point8_labels
...,...,...,...,...,...,...,...,...,...,...,...,...
4270-0,4322,23,1479,61793.0,519.0,1018.0,125.0,carcinoma,21d7,Tcell_CD4,0,point23_labels
4271-0,4323,23,1480,61794.0,929.0,1018.0,190.0,carcinoma,21d7,Imm_other,0,point23_labels
4272-0,4324,23,1481,61795.0,999.0,1019.0,173.0,carcinoma,21d7,Imm_other,0,point23_labels
4273-0,4325,23,1482,61796.0,322.0,1018.0,181.0,carcinoma,21d7,Myeloid_CD11c,0,point23_labels
4274-0,4326,23,1483,61797.0,785.0,1019.0,178.0,carcinoma,21d7,Tcell_CD4,0,point23_labels